"""Declarative, additive Oracle schema migrations.

The declarations in this module are deliberately data-only.  Both a clean
``init_schema`` and the startup migrator consume the same Phase 3 definitions,
which prevents a fresh database and an upgraded database from drifting.
"""

from __future__ import annotations


P3_MIGRATION_ID = "P3_001_DATA_QUALITY"
# This is a released migration identifier, not a checksum calculated at runtime.
# Changing it would make an already-applied database appear to have a different
# migration, so keep it immutable.
P3_MIGRATION_CHECKSUM = "d976f9dd4e0f1d8d45c4ab280b49c5414995d857d984e7ef885cd59c073d71e7"
P3_MIGRATION_DESCRIPTION = "Phase 3 raw collection, normalized snapshots, quality and diff history"

P3_TABLES: tuple[tuple[str, str], ...] = (
    ("SJZQ_SCHEMA_MIGRATION", """
        CREATE TABLE SJZQ_SCHEMA_MIGRATION (
            VERSION_ID VARCHAR2(64) NOT NULL,
            CHECKSUM VARCHAR2(64) NOT NULL,
            DESCRIPTION VARCHAR2(512) NOT NULL,
            STATUS VARCHAR2(16) NOT NULL,
            STARTED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
            APPLIED_AT TIMESTAMP,
            ERROR_MESSAGE VARCHAR2(2000),
            CONSTRAINT PK_SJZQ_SCHEMA_MIGRATION PRIMARY KEY (VERSION_ID)
        )
    """),
    ("SJZQ_PRODUCT_MASTER", """
        CREATE TABLE SJZQ_PRODUCT_MASTER (
            MASTER_PRODUCT_ID NUMBER(18) NOT NULL,
            PLATFORM_CODE VARCHAR2(32) NOT NULL,
            PLATFORM_PRODUCT_ID VARCHAR2(128) NOT NULL,
            FIRST_SEEN_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
            LAST_SEEN_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
            STATUS VARCHAR2(16) DEFAULT 'active' NOT NULL,
            CREATE_TIME TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
            UPDATE_TIME TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
            CONSTRAINT PK_SJZQ_PRODUCT_MASTER PRIMARY KEY (MASTER_PRODUCT_ID),
            CONSTRAINT UK_SJZQ_MASTER_PLATFORM UNIQUE (PLATFORM_CODE, PLATFORM_PRODUCT_ID)
        )
    """),
    ("SJZQ_RAW_COLLECTION", """
        CREATE TABLE SJZQ_RAW_COLLECTION (
            RAW_ID NUMBER(18) NOT NULL,
            REQUEST_KEY VARCHAR2(128) NOT NULL,
            TASK_ID NUMBER(18),
            JOB_ID NUMBER(18),
            ATTEMPT_ID NUMBER(18),
            DEVICE_ID NUMBER(18),
            SOURCE_TYPE VARCHAR2(32) NOT NULL,
            PAYLOAD_SHA256 VARCHAR2(64) NOT NULL,
            RAW_JSON CLOB NOT NULL,
            COLLECTED_AT TIMESTAMP NOT NULL,
            CREATE_TIME TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
            CONSTRAINT PK_SJZQ_RAW_COLLECTION PRIMARY KEY (RAW_ID),
            CONSTRAINT UK_SJZQ_RAW_REQUEST_KEY UNIQUE (REQUEST_KEY)
        )
    """),
    ("SJZQ_PRODUCT_SNAPSHOT", """
        CREATE TABLE SJZQ_PRODUCT_SNAPSHOT (
            SNAPSHOT_ID NUMBER(18) NOT NULL,
            MASTER_PRODUCT_ID NUMBER(18) NOT NULL,
            RAW_ID NUMBER(18) NOT NULL,
            LEGACY_PRODUCT_ID NUMBER(18),
            TASK_ID NUMBER(18),
            JOB_ID NUMBER(18),
            ATTEMPT_ID NUMBER(18),
            REQUEST_KEY VARCHAR2(128) NOT NULL,
            COLLECTED_AT TIMESTAMP NOT NULL,
            CONTENT_SHA256 VARCHAR2(64) NOT NULL,
            NORMALIZED_JSON CLOB NOT NULL,
            TITLE VARCHAR2(512),
            SHOP_NAME VARCHAR2(256),
            SHOP_ID VARCHAR2(64),
            AVAILABILITY VARCHAR2(32),
            PRICE NUMBER(18,4),
            DISPLAY_PRICE NUMBER(18,4),
            GROUP_PRICE NUMBER(18,4),
            DEAL_PRICE NUMBER(18,4),
            ORIGINAL_PRICE NUMBER(18,4),
            SALES_NUM NUMBER(12),
            SKU_JSON CLOB,
            FIELD_SOURCES CLOB,
            PARSER_VERSION VARCHAR2(64),
            QUALITY_RULES_VERSION VARCHAR2(64),
            PARSE_STATUS VARCHAR2(16),
            PAGE_STATUS VARCHAR2(32),
            QUALITY_STATUS VARCHAR2(16),
            PREVIOUS_SNAPSHOT_ID NUMBER(18),
            CREATE_TIME TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
            CONSTRAINT PK_SJZQ_PRODUCT_SNAPSHOT PRIMARY KEY (SNAPSHOT_ID),
            CONSTRAINT UK_SJZQ_SNAPSHOT_REQUEST UNIQUE (REQUEST_KEY),
            CONSTRAINT FK_SJZQ_SNAP_MASTER FOREIGN KEY (MASTER_PRODUCT_ID)
                REFERENCES SJZQ_PRODUCT_MASTER(MASTER_PRODUCT_ID),
            CONSTRAINT FK_SJZQ_SNAP_RAW FOREIGN KEY (RAW_ID)
                REFERENCES SJZQ_RAW_COLLECTION(RAW_ID)
        )
    """),
    ("SJZQ_FIELD_PROVENANCE", """
        CREATE TABLE SJZQ_FIELD_PROVENANCE (
            PROVENANCE_ID NUMBER(18) NOT NULL,
            SNAPSHOT_ID NUMBER(18) NOT NULL,
            FIELD_NAME VARCHAR2(128) NOT NULL,
            SOURCE_TYPE VARCHAR2(32) NOT NULL,
            SOURCE_REF VARCHAR2(512),
            TRANSFORMATION VARCHAR2(512),
            CONSTRAINT PK_SJZQ_FIELD_PROVENANCE PRIMARY KEY (PROVENANCE_ID),
            CONSTRAINT UK_SJZQ_PROV_SNAP_FIELD UNIQUE (SNAPSHOT_ID, FIELD_NAME),
            CONSTRAINT FK_SJZQ_PROV_SNAPSHOT FOREIGN KEY (SNAPSHOT_ID)
                REFERENCES SJZQ_PRODUCT_SNAPSHOT(SNAPSHOT_ID)
        )
    """),
    ("SJZQ_QUALITY_RESULT", """
        CREATE TABLE SJZQ_QUALITY_RESULT (
            QUALITY_RESULT_ID NUMBER(18) NOT NULL,
            RAW_ID NUMBER(18) NOT NULL,
            SNAPSHOT_ID NUMBER(18),
            ACCEPTED NUMBER(1) NOT NULL,
            STATUS VARCHAR2(16) NOT NULL,
            PAGE_STATUS VARCHAR2(32) NOT NULL,
            PARSE_STATUS VARCHAR2(16) NOT NULL,
            QUALITY_STATUS VARCHAR2(16) NOT NULL,
            PARSER_VERSION VARCHAR2(64) NOT NULL,
            QUALITY_RULES_VERSION VARCHAR2(64) NOT NULL,
            MISSING_FIELDS_JSON CLOB,
            ERROR_CODES_JSON CLOB,
            WARNINGS_JSON CLOB,
            CREATE_TIME TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
            CONSTRAINT PK_SJZQ_QUALITY_RESULT PRIMARY KEY (QUALITY_RESULT_ID),
            CONSTRAINT UK_SJZQ_QUALITY_RAW UNIQUE (RAW_ID),
            CONSTRAINT FK_SJZQ_QUALITY_RAW FOREIGN KEY (RAW_ID)
                REFERENCES SJZQ_RAW_COLLECTION(RAW_ID),
            CONSTRAINT FK_SJZQ_QUALITY_SNAPSHOT FOREIGN KEY (SNAPSHOT_ID)
                REFERENCES SJZQ_PRODUCT_SNAPSHOT(SNAPSHOT_ID)
        )
    """),
    ("SJZQ_DATA_QUARANTINE", """
        CREATE TABLE SJZQ_DATA_QUARANTINE (
            QUARANTINE_ID NUMBER(18) NOT NULL,
            RAW_ID NUMBER(18) NOT NULL,
            QUALITY_RESULT_ID NUMBER(18) NOT NULL,
            MASTER_PRODUCT_ID NUMBER(18),
            TASK_ID NUMBER(18),
            JOB_ID NUMBER(18),
            ATTEMPT_ID NUMBER(18),
            REQUEST_KEY VARCHAR2(128) NOT NULL,
            PARSER_VERSION VARCHAR2(64),
            QUALITY_RULES_VERSION VARCHAR2(64),
            STATUS VARCHAR2(16) NOT NULL,
            FAILURE_REASON VARCHAR2(2000),
            ERROR_CODES_JSON CLOB,
            ERROR_MESSAGE CLOB,
            EVIDENCE_JSON CLOB,
            COLLECTED_AT TIMESTAMP NOT NULL,
            CREATE_TIME TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
            CONSTRAINT PK_SJZQ_DATA_QUARANTINE PRIMARY KEY (QUARANTINE_ID),
            CONSTRAINT UK_SJZQ_QUAR_RAW UNIQUE (RAW_ID),
            CONSTRAINT UK_SJZQ_QUAR_REQUEST UNIQUE (REQUEST_KEY),
            CONSTRAINT FK_SJZQ_QUAR_RAW FOREIGN KEY (RAW_ID)
                REFERENCES SJZQ_RAW_COLLECTION(RAW_ID),
            CONSTRAINT FK_SJZQ_QUAR_QUALITY FOREIGN KEY (QUALITY_RESULT_ID)
                REFERENCES SJZQ_QUALITY_RESULT(QUALITY_RESULT_ID),
            CONSTRAINT FK_SJZQ_QUAR_MASTER FOREIGN KEY (MASTER_PRODUCT_ID)
                REFERENCES SJZQ_PRODUCT_MASTER(MASTER_PRODUCT_ID)
        )
    """),
    ("SJZQ_SNAPSHOT_DIFF", """
        CREATE TABLE SJZQ_SNAPSHOT_DIFF (
            DIFF_ID NUMBER(18) NOT NULL,
            SNAPSHOT_ID NUMBER(18) NOT NULL,
            PREVIOUS_SNAPSHOT_ID NUMBER(18),
            MASTER_PRODUCT_ID NUMBER(18) NOT NULL,
            CHANGED_FIELDS_JSON CLOB NOT NULL,
            PRICE_CHANGED NUMBER(1) DEFAULT 0 NOT NULL,
            SALES_CHANGED NUMBER(1) DEFAULT 0 NOT NULL,
            SKU_CHANGED NUMBER(1) DEFAULT 0 NOT NULL,
            AVAILABILITY_CHANGED NUMBER(1) DEFAULT 0 NOT NULL,
            TITLE_CHANGED NUMBER(1) DEFAULT 0 NOT NULL,
            SHOP_CHANGED NUMBER(1) DEFAULT 0 NOT NULL,
            CREATE_TIME TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
            CONSTRAINT PK_SJZQ_SNAPSHOT_DIFF PRIMARY KEY (DIFF_ID),
            CONSTRAINT UK_SJZQ_DIFF_SNAPSHOT UNIQUE (SNAPSHOT_ID),
            CONSTRAINT FK_SJZQ_DIFF_SNAPSHOT FOREIGN KEY (SNAPSHOT_ID)
                REFERENCES SJZQ_PRODUCT_SNAPSHOT(SNAPSHOT_ID),
            CONSTRAINT FK_SJZQ_DIFF_MASTER FOREIGN KEY (MASTER_PRODUCT_ID)
                REFERENCES SJZQ_PRODUCT_MASTER(MASTER_PRODUCT_ID)
        )
    """),
)

P3_SEQUENCES = (
    "SJZQ_SEQ_PRODUCT_MASTER",
    "SJZQ_SEQ_RAW_COLLECTION",
    "SJZQ_SEQ_PRODUCT_SNAPSHOT",
    "SJZQ_SEQ_FIELD_PROVENANCE",
    "SJZQ_SEQ_QUALITY_RESULT",
    "SJZQ_SEQ_DATA_QUARANTINE",
    "SJZQ_SEQ_SNAPSHOT_DIFF",
)

P3_INDEXES: tuple[tuple[str, str], ...] = (
    ("IDX_SJZQ_RAW_TASK_JOB", "CREATE INDEX IDX_SJZQ_RAW_TASK_JOB ON SJZQ_RAW_COLLECTION(TASK_ID, JOB_ID, COLLECTED_AT)"),
    ("IDX_SJZQ_SNAP_MASTER_TIME", "CREATE INDEX IDX_SJZQ_SNAP_MASTER_TIME ON SJZQ_PRODUCT_SNAPSHOT(MASTER_PRODUCT_ID, COLLECTED_AT)"),
    ("IDX_SJZQ_SNAP_RAW", "CREATE INDEX IDX_SJZQ_SNAP_RAW ON SJZQ_PRODUCT_SNAPSHOT(RAW_ID)"),
    ("IDX_SJZQ_QUAR_STATUS", "CREATE INDEX IDX_SJZQ_QUAR_STATUS ON SJZQ_DATA_QUARANTINE(STATUS, COLLECTED_AT)"),
    ("IDX_SJZQ_DIFF_MASTER", "CREATE INDEX IDX_SJZQ_DIFF_MASTER ON SJZQ_SNAPSHOT_DIFF(MASTER_PRODUCT_ID, CREATE_TIME)"),
)

P3_ADDITIVE_COLUMNS: tuple[tuple[str, str, str], ...] = (
    ("SJZQ_UPLOAD_RECEIPT", "MASTER_PRODUCT_ID", "ALTER TABLE SJZQ_UPLOAD_RECEIPT ADD (MASTER_PRODUCT_ID NUMBER(18))"),
    ("SJZQ_UPLOAD_RECEIPT", "SNAPSHOT_ID", "ALTER TABLE SJZQ_UPLOAD_RECEIPT ADD (SNAPSHOT_ID NUMBER(18))"),
    ("SJZQ_UPLOAD_RECEIPT", "QUARANTINE_ID", "ALTER TABLE SJZQ_UPLOAD_RECEIPT ADD (QUARANTINE_ID NUMBER(18))"),
    ("SJZQ_PRODUCT", "MASTER_PRODUCT_ID", "ALTER TABLE SJZQ_PRODUCT ADD (MASTER_PRODUCT_ID NUMBER(18))"),
    ("SJZQ_PRODUCT", "SNAPSHOT_ID", "ALTER TABLE SJZQ_PRODUCT ADD (SNAPSHOT_ID NUMBER(18))"),
)

# Phase 4 is index-only: management queries remain read-only and reuse the
# Phase 2/3 facts.  Keep this as a distinct migration so already-applied P3
# checksums remain immutable.
P4_MIGRATION_ID = "P4_001_MANAGEMENT_INDEXES"
P4_MIGRATION_CHECKSUM = "b3eb8d65fe4de8a758f11a2edbec9e0c24e106e36779990231f315ca160a1f54"
P4_MIGRATION_DESCRIPTION = "Phase 4 stable pagination and trace lookup indexes"
P4_INDEXES: tuple[tuple[str, str], ...] = (
    ("IDX_SJZQ_EVT_ATTEMPT_TIME", "CREATE INDEX IDX_SJZQ_EVT_ATTEMPT_TIME ON SJZQ_JOB_EVENT(ATTEMPT_ID, CREATE_TIME, EVENT_ID)"),
    ("IDX_SJZQ_QUAR_TASK_TIME", "CREATE INDEX IDX_SJZQ_QUAR_TASK_TIME ON SJZQ_DATA_QUARANTINE(TASK_ID, COLLECTED_AT, QUARANTINE_ID)"),
    ("IDX_SJZQ_QUAR_JOB_TIME", "CREATE INDEX IDX_SJZQ_QUAR_JOB_TIME ON SJZQ_DATA_QUARANTINE(JOB_ID, COLLECTED_AT, QUARANTINE_ID)"),
    ("IDX_SJZQ_SNAP_MASTER_PAGE", "CREATE INDEX IDX_SJZQ_SNAP_MASTER_PAGE ON SJZQ_PRODUCT_SNAPSHOT(MASTER_PRODUCT_ID, COLLECTED_AT, SNAPSHOT_ID)"),
    ("IDX_SJZQ_TASK_PAGE", "CREATE INDEX IDX_SJZQ_TASK_PAGE ON SJZQ_TASK(CREATE_TIME, TASK_ID)"),
    ("IDX_SJZQ_PRODUCT_PAGE", "CREATE INDEX IDX_SJZQ_PRODUCT_PAGE ON SJZQ_PRODUCT(COLLECT_TIME, PRODUCT_ID)"),
    ("IDX_SJZQ_PRODUCT_TASK_PAGE", "CREATE INDEX IDX_SJZQ_PRODUCT_TASK_PAGE ON SJZQ_PRODUCT(TASK_ID, COLLECT_TIME, PRODUCT_ID)"),
)

# Phase 5 introduces the explicit tenant boundary.  The global product table is
# retained as an internal platform identity registry; tenant APIs address the
# enterprise-private mapping instead.
P5_MIGRATION_ID = "P5_001_ENTERPRISE_TENANCY"
P5_MIGRATION_CHECKSUM = "7ea4925b3933872548a6d45a17d76c8e0fe394a7bd268eca9fc953520f350677"
P5_MIGRATION_DESCRIPTION = "Enterprise, workspace, tenant RBAC, quota and private product ownership"

P5_TABLES: tuple[tuple[str, str], ...] = (
    ("SJZQ_ENTERPRISE", """
        CREATE TABLE SJZQ_ENTERPRISE (
            ENTERPRISE_ID NUMBER(18) NOT NULL, ENTERPRISE_CODE VARCHAR2(64) NOT NULL,
            ENTERPRISE_NAME VARCHAR2(256) NOT NULL, STATUS VARCHAR2(16) DEFAULT 'active' NOT NULL,
            RETENTION_DAYS NUMBER(10) DEFAULT 365 NOT NULL,
            CREATE_TIME TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
            UPDATE_TIME TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
            CONSTRAINT PK_SJZQ_ENTERPRISE PRIMARY KEY (ENTERPRISE_ID),
            CONSTRAINT UK_SJZQ_ENTERPRISE_CODE UNIQUE (ENTERPRISE_CODE),
            CONSTRAINT CK_SJZQ_ENTERPRISE_STATUS CHECK (STATUS IN ('active','suspended','deleting','deleted'))
        )
    """),
    ("SJZQ_WORKSPACE", """
        CREATE TABLE SJZQ_WORKSPACE (
            WORKSPACE_ID NUMBER(18) NOT NULL, ENTERPRISE_ID NUMBER(18) NOT NULL,
            WORKSPACE_CODE VARCHAR2(64) NOT NULL, WORKSPACE_NAME VARCHAR2(256) NOT NULL,
            STATUS VARCHAR2(16) DEFAULT 'active' NOT NULL,
            CREATE_TIME TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
            UPDATE_TIME TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
            CONSTRAINT PK_SJZQ_WORKSPACE PRIMARY KEY (WORKSPACE_ID),
            CONSTRAINT UK_SJZQ_WORKSPACE_CODE UNIQUE (ENTERPRISE_ID,WORKSPACE_CODE),
            CONSTRAINT UK_SJZQ_WORKSPACE_OWNER UNIQUE (ENTERPRISE_ID,WORKSPACE_ID),
            CONSTRAINT FK_SJZQ_WORKSPACE_ENT FOREIGN KEY (ENTERPRISE_ID) REFERENCES SJZQ_ENTERPRISE(ENTERPRISE_ID)
        )
    """),
    ("SJZQ_ENTERPRISE_MEMBERSHIP", """
        CREATE TABLE SJZQ_ENTERPRISE_MEMBERSHIP (
            MEMBERSHIP_ID NUMBER(18) NOT NULL, ENTERPRISE_ID NUMBER(18) NOT NULL,
            USER_ID NUMBER(18) NOT NULL, ROLE_ID NUMBER(18) NOT NULL,
            STATUS VARCHAR2(16) DEFAULT 'active' NOT NULL,
            CREATE_TIME TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
            UPDATE_TIME TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
            CONSTRAINT PK_SJZQ_ENT_MEMBERSHIP PRIMARY KEY (MEMBERSHIP_ID),
            CONSTRAINT UK_SJZQ_ENT_MEMBER UNIQUE (ENTERPRISE_ID,USER_ID),
            CONSTRAINT FK_SJZQ_ENT_MEMBER_ENT FOREIGN KEY (ENTERPRISE_ID) REFERENCES SJZQ_ENTERPRISE(ENTERPRISE_ID)
        )
    """),
    ("SJZQ_WORKSPACE_MEMBERSHIP", """
        CREATE TABLE SJZQ_WORKSPACE_MEMBERSHIP (
            ENTERPRISE_ID NUMBER(18) NOT NULL, WORKSPACE_ID NUMBER(18) NOT NULL,
            USER_ID NUMBER(18) NOT NULL, ROLE_ID NUMBER(18),
            CREATE_TIME TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
            CONSTRAINT PK_SJZQ_WS_MEMBERSHIP PRIMARY KEY (WORKSPACE_ID,USER_ID),
            CONSTRAINT FK_SJZQ_WS_MEMBER_WS FOREIGN KEY (ENTERPRISE_ID,WORKSPACE_ID)
                REFERENCES SJZQ_WORKSPACE(ENTERPRISE_ID,WORKSPACE_ID)
        )
    """),
    ("SJZQ_ENTERPRISE_QUOTA", """
        CREATE TABLE SJZQ_ENTERPRISE_QUOTA (
            ENTERPRISE_ID NUMBER(18) NOT NULL, MAX_WORKSPACES NUMBER(10) DEFAULT 10 NOT NULL,
            MAX_USERS NUMBER(10) DEFAULT 100 NOT NULL, MAX_ACTIVE_TASKS NUMBER(10) DEFAULT 100 NOT NULL,
            MAX_DAILY_SNAPSHOTS NUMBER(18) DEFAULT 100000 NOT NULL,
            STORAGE_BYTES NUMBER(18) DEFAULT 107374182400 NOT NULL,
            UPDATE_TIME TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
            CONSTRAINT PK_SJZQ_ENTERPRISE_QUOTA PRIMARY KEY (ENTERPRISE_ID),
            CONSTRAINT FK_SJZQ_QUOTA_ENT FOREIGN KEY (ENTERPRISE_ID) REFERENCES SJZQ_ENTERPRISE(ENTERPRISE_ID)
        )
    """),
    ("SJZQ_ENTERPRISE_PRODUCT", """
        CREATE TABLE SJZQ_ENTERPRISE_PRODUCT (
            ENTERPRISE_PRODUCT_ID NUMBER(18) NOT NULL, ENTERPRISE_ID NUMBER(18) NOT NULL,
            IDENTITY_ID NUMBER(18) NOT NULL, STATUS VARCHAR2(16) DEFAULT 'active' NOT NULL,
            RETENTION_STATE VARCHAR2(16) DEFAULT 'normal' NOT NULL, DELETED_AT TIMESTAMP,
            CREATE_TIME TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
            UPDATE_TIME TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
            CONSTRAINT PK_SJZQ_ENTERPRISE_PRODUCT PRIMARY KEY (ENTERPRISE_PRODUCT_ID),
            CONSTRAINT UK_SJZQ_ENT_PRODUCT UNIQUE (ENTERPRISE_ID,IDENTITY_ID),
            CONSTRAINT UK_SJZQ_ENT_PRODUCT_OWNER UNIQUE (ENTERPRISE_ID,ENTERPRISE_PRODUCT_ID),
            CONSTRAINT FK_SJZQ_ENT_PRODUCT_ENT FOREIGN KEY (ENTERPRISE_ID) REFERENCES SJZQ_ENTERPRISE(ENTERPRISE_ID),
            CONSTRAINT FK_SJZQ_ENT_PRODUCT_ID FOREIGN KEY (IDENTITY_ID) REFERENCES SJZQ_PRODUCT_MASTER(MASTER_PRODUCT_ID)
        )
    """),
)

P5_SEQUENCES = ("SJZQ_SEQ_ENTERPRISE", "SJZQ_SEQ_WORKSPACE", "SJZQ_SEQ_ENT_MEMBERSHIP", "SJZQ_SEQ_ENTERPRISE_PRODUCT")

P5_TENANT_COLUMNS: tuple[tuple[str, str], ...] = (
    ("SJZQ_DEVICE", "ENTERPRISE_ID NUMBER(18), WORKSPACE_ID NUMBER(18)"),
    ("SJZQ_TASK", "ENTERPRISE_ID NUMBER(18), WORKSPACE_ID NUMBER(18)"),
    ("SJZQ_COLLECTION_JOB", "ENTERPRISE_ID NUMBER(18), WORKSPACE_ID NUMBER(18)"),
    ("SJZQ_COLLECTION_ATTEMPT", "ENTERPRISE_ID NUMBER(18), WORKSPACE_ID NUMBER(18)"),
    ("SJZQ_COLLECTION_LEASE", "ENTERPRISE_ID NUMBER(18), WORKSPACE_ID NUMBER(18)"),
    ("SJZQ_COLLECTION_CHECKPOINT", "ENTERPRISE_ID NUMBER(18), WORKSPACE_ID NUMBER(18)"),
    ("SJZQ_COLLECTION_OUTBOX", "ENTERPRISE_ID NUMBER(18), WORKSPACE_ID NUMBER(18)"),
    ("SJZQ_JOB_EVENT", "ENTERPRISE_ID NUMBER(18), WORKSPACE_ID NUMBER(18)"),
    ("SJZQ_TASK_ITEM", "ENTERPRISE_ID NUMBER(18), WORKSPACE_ID NUMBER(18)"),
    ("SJZQ_TASK_LOG", "ENTERPRISE_ID NUMBER(18), WORKSPACE_ID NUMBER(18)"),
    ("SJZQ_UPLOAD_RECEIPT", "ENTERPRISE_ID NUMBER(18), WORKSPACE_ID NUMBER(18)"),
    ("SJZQ_PRODUCT", "ENTERPRISE_ID NUMBER(18), WORKSPACE_ID NUMBER(18), ENTERPRISE_PRODUCT_ID NUMBER(18)"),
    ("SJZQ_PRODUCT_IMAGE", "ENTERPRISE_ID NUMBER(18), WORKSPACE_ID NUMBER(18)"),
    ("SJZQ_RAW_COLLECTION", "ENTERPRISE_ID NUMBER(18), WORKSPACE_ID NUMBER(18)"),
    ("SJZQ_PRODUCT_SNAPSHOT", "ENTERPRISE_ID NUMBER(18), WORKSPACE_ID NUMBER(18), ENTERPRISE_PRODUCT_ID NUMBER(18)"),
    ("SJZQ_QUALITY_RESULT", "ENTERPRISE_ID NUMBER(18), WORKSPACE_ID NUMBER(18)"),
    ("SJZQ_DATA_QUARANTINE", "ENTERPRISE_ID NUMBER(18), WORKSPACE_ID NUMBER(18), ENTERPRISE_PRODUCT_ID NUMBER(18)"),
    ("SJZQ_SNAPSHOT_DIFF", "ENTERPRISE_ID NUMBER(18), WORKSPACE_ID NUMBER(18), ENTERPRISE_PRODUCT_ID NUMBER(18)"),
    ("SJZQ_OP_LOG", "ENTERPRISE_ID NUMBER(18), WORKSPACE_ID NUMBER(18)"),
    ("SJZQ_PLATFORM_ACCOUNT", "ENTERPRISE_ID NUMBER(18), WORKSPACE_ID NUMBER(18)"),
    ("SJZQ_ALERT", "ENTERPRISE_ID NUMBER(18), WORKSPACE_ID NUMBER(18)"),
)

P5_INDEXES: tuple[tuple[str, str], ...] = (
    ("IDX_SJZQ_TASK_TENANT_PAGE", "CREATE INDEX IDX_SJZQ_TASK_TENANT_PAGE ON SJZQ_TASK(ENTERPRISE_ID,WORKSPACE_ID,CREATE_TIME,TASK_ID)"),
    ("IDX_SJZQ_JOB_TENANT", "CREATE INDEX IDX_SJZQ_JOB_TENANT ON SJZQ_COLLECTION_JOB(ENTERPRISE_ID,WORKSPACE_ID,TASK_ID,STATUS)"),
    ("IDX_SJZQ_PRODUCT_TENANT_PAGE", "CREATE INDEX IDX_SJZQ_PRODUCT_TENANT_PAGE ON SJZQ_PRODUCT(ENTERPRISE_ID,WORKSPACE_ID,COLLECT_TIME,PRODUCT_ID)"),
    ("IDX_SJZQ_SNAPSHOT_TENANT", "CREATE INDEX IDX_SJZQ_SNAPSHOT_TENANT ON SJZQ_PRODUCT_SNAPSHOT(ENTERPRISE_ID,WORKSPACE_ID,ENTERPRISE_PRODUCT_ID,COLLECTED_AT,SNAPSHOT_ID)"),
    ("IDX_SJZQ_QUAR_TENANT", "CREATE INDEX IDX_SJZQ_QUAR_TENANT ON SJZQ_DATA_QUARANTINE(ENTERPRISE_ID,WORKSPACE_ID,STATUS,COLLECTED_AT,QUARANTINE_ID)"),
    ("IDX_SJZQ_QUALITY_TENANT", "CREATE INDEX IDX_SJZQ_QUALITY_TENANT ON SJZQ_QUALITY_RESULT(ENTERPRISE_ID,WORKSPACE_ID,CREATE_TIME)"),
    ("IDX_SJZQ_EVENT_TENANT", "CREATE INDEX IDX_SJZQ_EVENT_TENANT ON SJZQ_JOB_EVENT(ENTERPRISE_ID,WORKSPACE_ID,TASK_ID,CREATE_TIME,EVENT_ID)"),
)

P5_FENCE_MIGRATION_ID = "P5_002_TENANT_NOT_NULL"
P5_FENCE_MIGRATION_CHECKSUM = "b445b0349662890395786e392274518ecacae34215629f9dffb444148218e803"
P5_FENCE_MIGRATION_DESCRIPTION = "Enforce non-null tenant ownership on private facts"
P5_COMPAT_MIGRATION_ID = "P5_003_LEGACY_TENANT_DEFAULTS"
P5_COMPAT_MIGRATION_CHECKSUM = "df842e1970b77d158013298462f426588409508f018523ca4de5be7fa377797f"
P5_COMPAT_MIGRATION_DESCRIPTION = "Preserve Phase 1-4 fixture inserts with deterministic legacy tenant defaults"

# Phase 5.5 closes the enterprise hardening gaps without changing the Phase 6
# product scope.  Enrollment bearer values are stored only as SHA-256 hashes;
# quota mutations are serialized through one usage row and leave an immutable
# event ledger plus an idempotent resource reservation.
P55_MIGRATION_ID = "P5_5_001_ENTERPRISE_HARDENING"
P55_MIGRATION_CHECKSUM = "8b1b3ddb1588c9a3cc03ae9a322a3a5e7c8564a211bd48a83dec70efd54ef303"
P55_MIGRATION_DESCRIPTION = "One-time device enrollment, revocation, and transactional quota ledger"

P55_TABLES: tuple[tuple[str, str], ...] = (
    ("SJZQ_DEVICE_ENROLL_TOKEN", """
        CREATE TABLE SJZQ_DEVICE_ENROLL_TOKEN (
            TOKEN_ID NUMBER(18) NOT NULL, ENTERPRISE_ID NUMBER(18) NOT NULL,
            WORKSPACE_ID NUMBER(18) NOT NULL, TOKEN_HASH VARCHAR2(64) NOT NULL,
            STATUS VARCHAR2(16) DEFAULT 'active' NOT NULL, EXPIRES_AT TIMESTAMP NOT NULL,
            ISSUED_BY NUMBER(18), USED_BY_DEVICE_ID NUMBER(18), USED_AT TIMESTAMP,
            REVOKED_AT TIMESTAMP, REPLACED_BY_TOKEN_ID NUMBER(18),
            CREATE_TIME TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
            CONSTRAINT PK_SJZQ_DEVICE_ENROLL PRIMARY KEY (TOKEN_ID),
            CONSTRAINT UK_SJZQ_DEVICE_ENROLL_HASH UNIQUE (TOKEN_HASH),
            CONSTRAINT CK_SJZQ_DEVICE_ENROLL_STATUS CHECK (STATUS IN ('active','used','revoked','expired')),
            CONSTRAINT FK_SJZQ_DEVICE_ENROLL_WS FOREIGN KEY (ENTERPRISE_ID,WORKSPACE_ID)
                REFERENCES SJZQ_WORKSPACE(ENTERPRISE_ID,WORKSPACE_ID)
        )
    """),
    ("SJZQ_QUOTA_USAGE", """
        CREATE TABLE SJZQ_QUOTA_USAGE (
            ENTERPRISE_ID NUMBER(18) NOT NULL, METRIC_CODE VARCHAR2(32) NOT NULL,
            PERIOD_KEY VARCHAR2(16) NOT NULL, USED_VALUE NUMBER(18) DEFAULT 0 NOT NULL,
            RESERVED_VALUE NUMBER(18) DEFAULT 0 NOT NULL, VERSION_NO NUMBER(18) DEFAULT 0 NOT NULL,
            UPDATE_TIME TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
            CONSTRAINT PK_SJZQ_QUOTA_USAGE PRIMARY KEY (ENTERPRISE_ID,METRIC_CODE,PERIOD_KEY),
            CONSTRAINT CK_SJZQ_QUOTA_USAGE_POS CHECK (USED_VALUE >= 0 AND RESERVED_VALUE >= 0),
            CONSTRAINT CK_SJZQ_QUOTA_USAGE_METRIC CHECK (METRIC_CODE IN ('active_task','daily_snapshot','storage_bytes')),
            CONSTRAINT FK_SJZQ_QUOTA_USAGE_ENT FOREIGN KEY (ENTERPRISE_ID) REFERENCES SJZQ_ENTERPRISE(ENTERPRISE_ID)
        )
    """),
    ("SJZQ_QUOTA_RESERVATION", """
        CREATE TABLE SJZQ_QUOTA_RESERVATION (
            RESERVATION_ID NUMBER(18) NOT NULL, ENTERPRISE_ID NUMBER(18) NOT NULL,
            WORKSPACE_ID NUMBER(18) NOT NULL, METRIC_CODE VARCHAR2(32) NOT NULL,
            PERIOD_KEY VARCHAR2(16) NOT NULL, AMOUNT NUMBER(18) NOT NULL,
            RESOURCE_TYPE VARCHAR2(32) NOT NULL, RESOURCE_KEY VARCHAR2(128) NOT NULL,
            STATUS VARCHAR2(16) DEFAULT 'held' NOT NULL, EXPIRES_AT TIMESTAMP,
            COMMITTED_AT TIMESTAMP, RELEASED_AT TIMESTAMP,
            CREATE_TIME TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
            CONSTRAINT PK_SJZQ_QUOTA_RESERVATION PRIMARY KEY (RESERVATION_ID),
            CONSTRAINT UK_SJZQ_QUOTA_RESOURCE UNIQUE (ENTERPRISE_ID,METRIC_CODE,PERIOD_KEY,RESOURCE_TYPE,RESOURCE_KEY),
            CONSTRAINT CK_SJZQ_QUOTA_RES_STATUS CHECK (STATUS IN ('held','committed','released','expired')),
            CONSTRAINT CK_SJZQ_QUOTA_RES_AMOUNT CHECK (AMOUNT > 0),
            CONSTRAINT CK_SJZQ_QUOTA_RES_METRIC CHECK (METRIC_CODE IN ('active_task','daily_snapshot','storage_bytes')),
            CONSTRAINT FK_SJZQ_QUOTA_RES_WS FOREIGN KEY (ENTERPRISE_ID,WORKSPACE_ID)
                REFERENCES SJZQ_WORKSPACE(ENTERPRISE_ID,WORKSPACE_ID)
        )
    """),
    ("SJZQ_QUOTA_LEDGER", """
        CREATE TABLE SJZQ_QUOTA_LEDGER (
            LEDGER_ID NUMBER(18) NOT NULL, ENTERPRISE_ID NUMBER(18) NOT NULL,
            WORKSPACE_ID NUMBER(18) NOT NULL, METRIC_CODE VARCHAR2(32) NOT NULL,
            PERIOD_KEY VARCHAR2(16) NOT NULL, EVENT_TYPE VARCHAR2(24) NOT NULL,
            EVENT_KEY VARCHAR2(192) NOT NULL, DELTA_USED NUMBER(18) DEFAULT 0 NOT NULL,
            DELTA_RESERVED NUMBER(18) DEFAULT 0 NOT NULL, RESOURCE_TYPE VARCHAR2(32),
            RESOURCE_KEY VARCHAR2(128), CREATE_TIME TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
            CONSTRAINT PK_SJZQ_QUOTA_LEDGER PRIMARY KEY (LEDGER_ID),
            CONSTRAINT UK_SJZQ_QUOTA_LEDGER_EVENT UNIQUE (EVENT_KEY),
            CONSTRAINT FK_SJZQ_QUOTA_LEDGER_WS FOREIGN KEY (ENTERPRISE_ID,WORKSPACE_ID)
                REFERENCES SJZQ_WORKSPACE(ENTERPRISE_ID,WORKSPACE_ID)
        )
    """),
)

P55_SEQUENCES = (
    "SJZQ_SEQ_DEVICE_ENROLL", "SJZQ_SEQ_QUOTA_RESERVATION", "SJZQ_SEQ_QUOTA_LEDGER",
)

P55_INDEXES: tuple[tuple[str, str], ...] = (
    ("IDX_SJZQ_ENROLL_SCOPE", "CREATE INDEX IDX_SJZQ_ENROLL_SCOPE ON SJZQ_DEVICE_ENROLL_TOKEN(ENTERPRISE_ID,WORKSPACE_ID,STATUS,EXPIRES_AT)"),
    ("IDX_SJZQ_QUOTA_RES_STATUS", "CREATE INDEX IDX_SJZQ_QUOTA_RES_STATUS ON SJZQ_QUOTA_RESERVATION(ENTERPRISE_ID,METRIC_CODE,STATUS,EXPIRES_AT)"),
    ("IDX_SJZQ_QUOTA_LEDGER_SCOPE", "CREATE INDEX IDX_SJZQ_QUOTA_LEDGER_SCOPE ON SJZQ_QUOTA_LEDGER(ENTERPRISE_ID,WORKSPACE_ID,METRIC_CODE,CREATE_TIME)"),
)

P55_DEVICE_COLUMNS: tuple[tuple[str, str, str], ...] = (
    ("SJZQ_DEVICE", "REVOKED_AT", "ALTER TABLE SJZQ_DEVICE ADD (REVOKED_AT TIMESTAMP)"),
    ("SJZQ_DEVICE", "REVOKED_BY", "ALTER TABLE SJZQ_DEVICE ADD (REVOKED_BY NUMBER(18))"),
    ("SJZQ_DEVICE", "DEVICE_KEY_ROTATED_AT", "ALTER TABLE SJZQ_DEVICE ADD (DEVICE_KEY_ROTATED_AT TIMESTAMP)"),
    ("SJZQ_DEVICE", "ENROLLMENT_TOKEN_ID", "ALTER TABLE SJZQ_DEVICE ADD (ENROLLMENT_TOKEN_ID NUMBER(18))"),
)
